- hosts: all 
  remote_user: ansible
  become: yes
  tasks: 
  - name: download zabbix repo in centos 
    yum:
      name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
      state: present 
    notify: 
     - start zabbix agent
     - restart zabbix agent 
  handlers: 
  - name: start zabbix agent 
    service: 
      name: zabbix-agent
      state: started 
  - name: restart zabbix agent 
    service: 
      name: zabbix-agent
      state: restarted 
      enabled: yes

