- hosts: all
  become: yes 
  tasks: 
  - name: download repo in ubuntu 
    get_url:
      url: wget https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+xenial_all.deb
      dest: /home/user 
  - name: install package in ubuntu 
    apt:
      deb: /home/user/zabbix-release_5.0-1+xenial_all.deb  
  - name: install zabbix-agent  in ubuntu 
    apt:
      name: zabbix-agent
      state: present 
      update_cache: yes 
    notify: 
     - restart zabbix agent
  handlers: 
  - name: restart zabbix agent 
    service: 
      name: zabbix-agent
      state: restarted 
      enabled: yes
