apiVersion: v1
kind: Pod
metadata:
  name: tomcat-nginx  ## Pod name
  labels: 
   app: tomcat
   web: nginx
spec:   ## input section
  containers:    ## pod input is container  list
    - name: app-container
      image: tomcat:8
      ports:
      - containerPort: 8080
        name: appserver-port  
        protocol: TCP
    - name: web-container
      image: nginx
      ports:
      - containerPort: 80
        name: webserver-port
        protocol: TCP