apiVersion: v1
kind: ReplicationController
metadata: 
  name: rc-app  ## RC name
spec:   ## Replication controller input  
  replicas: 5  ## number of replicas 
  selector:  ## select the pod for replicating by using Label
    rc: app
  template:   ## define Pod information   
    metadata: 
      name: pod-rc  ## pod name
      labels:
        rc: app
    spec: ## container info  or Pod input
      containers:
        - image: tomcat:8
          name: app-server-container  ## container name
          ports:
          - containerPort: 8080