apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: rs-app
spec:
  replicas: 2
  selector: 
    matchLabels:
     rs: app
  template: 
    metadata:
      name: pod-rs-app
      labels:
        rs: app
    spec:   
      containers:
      - name: rc-app-c1
        image: tomcat:8

        