--- 
- hosts: all 
  become: yes 
  vars:
   - package_ubuntu_name: apache2
   - package_centos_name: httpd
   - centos_php_packages: ["php" ,"php-mysql"]
   - ubuntu_php_packages: ["php", "libapache2-mod-php", "php-mcrypt" ,"php-mysql"]
   - path: info.php
  tasks: 
  - name: install apache2 on ubuntu 
    apt: 
      name: "{{ package_ubuntu_name }}"
      state: present 
      update_cache: yes
    notify: 
     - restart service apache2
    when: ansible_os_family == "Debian"
  - name: install httpd on centos 
    yum: 
      name: "{{ package_centos_name }}"
      state: present 
    when:  ansible_os_family == "RedHat"
    notify:
     - restart service httpd
  - name: install php packages on ubuntu
    apt: 
     name: "{{ ubuntu_php_packages }}"
     state: present
    notify: 
     - restart service apache2
    when: ansible_os_family == "Debian"
  - name: install php packages on centos
    yum:
     name: "{{ centos_php_packages }}"
     state: present 
    notify: 
     - restart service httpd
    when: ansible_os_family == "RedHat" 
  - name:  copy content into nodes
    copy:
     content: '<?php phpinfo(); ?>'
     dest: /var/www/html/"{{ path }}"

  handlers:
   - name: restart service apache2
     service: 
       name: "{{ package_ubuntu_name }}"
       state: restarted
   - name: restart service httpd
     service:
       name:  "{{ package_centos_name }}"
       state: restarted   